IBX-1190: Updated readme to fit new template
ezsystems/ezplatform-admin-ui-assets pull request #31
Opened 2021-10-18 13:11 UTC by juskora

| Question                                  | Answer
| ----------------------------------------- | ------------------
| **JIRA issue**                            | https://issues.ibexa.co/browse/IBX-1190
| **Type**                                  | improvement
| **Target Ibexa DXP version**              | `v3.3`
| **BC breaks**                             | no

Updates the README with new template.

2021-10-18 13:22 UTC, DominikaK approved these changes

2021-10-18 13:37 UTC, dew326 requested changes

2021-10-18 13:37 UTC, dew326 commented on README.md
> -## Installing dependencies
This is important part of this package, I don't think it should be removed

2021-10-18 13:37 UTC, dew326 commented on README.md
> -## Preparing a tag for release
This as well

2021-10-19 10:13 UTC, dew326 approved these changes

2021-10-20 07:31 UTC, merged